from __future__ import annotations

from uuid import UUID

import pytest

from wto_desktop_agent.platforms.linux.capture import CaptureRequest
from wto_desktop_agent.platforms.linux.capture_fingerprint import (
    CAPTURE_REQUEST_FIELD_CLASSIFICATION,
    CaptureExecutionPlan,
    canonical_capture_fingerprint,
    canonical_capture_fingerprint_v1,
)

TASK_ID = UUID("10000000-0000-4000-8000-000000000071")
EXECUTION_ID = UUID("20000000-0000-4000-8000-000000000071")
IDEMPOTENCY_KEY = UUID("30000000-0000-4000-8000-000000000071")


def _request(**overrides: object) -> CaptureRequest:
    values: dict[str, object] = {
        "task_id": TASK_ID,
        "execution_id": EXECUTION_ID,
        "idempotency_key": IDEMPOTENCY_KEY,
        "interface": "wlan1",
        "channel": 36,
        "frequency_mhz": 5180,
        "width_mhz": 20,
        "duration_seconds": 5,
        "max_size_bytes": 4096,
        "capture_format": "pcapng",
        "radiotap": True,
        "snapshot_length": 262_144,
    }
    values.update(overrides)
    return CaptureRequest.model_validate(values)


def _plan(request: CaptureRequest, *, provider: str = "linux-dumpcap") -> CaptureExecutionPlan:
    size_kib = max(1, request.max_size_bytes // 1024)
    return CaptureExecutionPlan(
        provider=provider,
        method="radiotap-frequency-lock",
        effective_size_limit_bytes=size_kib * 1024,
        effective_dumpcap_arguments=(
            "-q",
            "-i",
            request.interface,
            "-I",
            "-y",
            "IEEE802_11_RADIO",
            "-F",
            request.capture_format,
            "-s",
            str(request.snapshot_length),
            "-a",
            f"duration:{request.duration_seconds}",
            "-a",
            f"filesize:{size_kib}",
            "-w",
            "-",
        ),
    )


def _fingerprint(request: CaptureRequest, *, provider: str = "linux-dumpcap") -> str:
    return canonical_capture_fingerprint(request, _plan(request, provider=provider)).sha256


@pytest.mark.parametrize(
    "overrides",
    (
        {"interface": "wlan2"},
        {"channel": 40, "frequency_mhz": 5200},
        {"width_mhz": 80},
        {"duration_seconds": 6},
        {"max_size_bytes": 5120},
        {"capture_format": "pcap"},
        {"snapshot_length": 65_535},
    ),
)
def test_every_mutable_functional_request_field_changes_fingerprint(
    overrides: dict[str, object],
) -> None:
    baseline = _request()
    changed = _request(**overrides)
    assert _fingerprint(changed) != _fingerprint(baseline)


def test_logical_ids_do_not_change_functional_fingerprint() -> None:
    baseline = _request()
    changed = _request(
        task_id=UUID("10000000-0000-4000-8000-000000000072"),
        execution_id=UUID("20000000-0000-4000-8000-000000000072"),
        idempotency_key=UUID("30000000-0000-4000-8000-000000000072"),
    )
    assert _fingerprint(changed) == _fingerprint(baseline)


def test_provider_and_effective_arguments_are_functional() -> None:
    request = _request()
    baseline = canonical_capture_fingerprint(request, _plan(request))
    provider_changed = canonical_capture_fingerprint(
        request, _plan(request, provider="another-semantic-provider")
    )
    args_changed = canonical_capture_fingerprint(
        request,
        CaptureExecutionPlan(
            provider="linux-dumpcap",
            method="radiotap-frequency-lock",
            effective_size_limit_bytes=4096,
            effective_dumpcap_arguments=(*_plan(request).effective_dumpcap_arguments, "--x"),
        ),
    )
    assert baseline.sha256 != provider_changed.sha256
    assert baseline.sha256 != args_changed.sha256
    assert "provider_version" not in baseline.document["capture_semantics"]


def test_v2_fingerprint_persists_complete_channel_geometry() -> None:
    request = _request(width_mhz=80)
    fingerprint = canonical_capture_fingerprint(request, _plan(request))

    assert fingerprint.version == "capture-functional-v2"
    assert fingerprint.document["derived"] == {
        "band": "5GHz",
        "primary_channel": 36,
        "control_frequency_mhz": 5180,
        "width_mhz": 80,
        "center_frequency_1_mhz": 5210,
        "center_frequency_2_mhz": None,
        "geometry_version": "linux-channel-geometry-v1",
    }


def test_legacy_v1_is_available_only_for_unambiguous_20_mhz_reuse() -> None:
    request = _request()
    legacy = canonical_capture_fingerprint_v1(request, _plan(request))

    assert legacy.version == "capture-functional-v1"
    # Golden generated by the shipped Phase 07 v1 canonicalizer before CF1/CF2
    # became part of the effective channel identity.  This prevents a new v1
    # helper from merely being self-consistent while breaking durable reuse.
    assert legacy.sha256 == ("58f5a020953a69329cf8d8e358f2323f3497b6bbacbe2fc0bb0f311975ce5eeb")
    assert legacy.sha256 != canonical_capture_fingerprint(request, _plan(request)).sha256
    with pytest.raises(ValueError, match="ambiguous"):
        canonical_capture_fingerprint_v1(_request(width_mhz=80), _plan(_request(width_mhz=80)))


def test_capture_request_classification_is_exhaustive_and_future_fields_fail_closed() -> None:
    classified = frozenset().union(*CAPTURE_REQUEST_FIELD_CLASSIFICATION.values())
    assert classified == frozenset(CaptureRequest.model_fields)

    class ExtendedCaptureRequest(CaptureRequest):
        presentation_label: str = "future"

    future = ExtendedCaptureRequest.model_validate(_request().model_dump(mode="python"))
    with pytest.raises(RuntimeError, match="classification is incomplete"):
        canonical_capture_fingerprint(future, _plan(future))
